import SideNavigation from "@/components/dashboard/navigation/SideNavigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section className="flex gap-2 h-screen min-h-[400px] overflow-auto">
      <SideNavigation />
      <div className="flex-1 h-full overflow-auto">
        {children}
      </div>
    </section>
  )
}
